In [12]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder

In [3]:
# loading dataset and basic stats
df = pd.read_csv("student_data.csv")
df.head()

    Name  Gender Department   Age  CGPA  Attendance
0   Amit    Male        CSE  20.0   8.5        90.0
1  Priya  Female         IT  21.0   9.1        95.0
2  Rahul    Male        ECE  20.0   7.8        85.0
3  Sneha  Female        CSE  22.0   8.9        92.0
4  Karan    Male         IT  21.0   NaN        88.0

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        10 non-null     str
 1   Gender      10 non-null     str
 2   Department  10 non-null     str
 3   Age         8 non-null      float64
 4   CGPA        9 non-null      float64
 5   Attendance  9 non-null      float64
dtypes: float64(3), str(3)
memory usage: 612.0 bytes

In [5]:
df.describe()

             Age      CGPA  Attendance
count   8.000000  9.000000    9.000000
mean   20.875000  8.566667   91.111111
std     0.834523  0.616441    3.551213
min    20.000000  7.500000   85.000000
25%    20.000000  8.200000   89.000000
50%    21.000000  8.800000   91.000000
75%    21.250000  9.000000   94.000000
max    22.000000  9.300000   96.000000

In [6]:
# handling missing data
df.isnull().sum()

Name          0
Gender        0
Department    0
Age           2
CGPA          1
Attendance    1
dtype: int64

In [9]:
# filling age with median
df["Age"] = df["Age"].fillna(df["Age"].median())

#  filling cgpa with median
df["CGPA"] = df["CGPA"].fillna(df["CGPA"].median())

# filling attendance with mean
df["Attendance"] = df["Attendance"].fillna(df["Attendance"].mean())

In [10]:
df.isnull().sum()

Name          0
Gender        0
Department    0
Age           0
CGPA          0
Attendance    0
dtype: int64

In [13]:
#  encoding categorical variables
#  applying label encoding to gender
le = LabelEncoder()
df["Gender"] = le.fit_transform(df["Gender"])

     Name  Gender Department   Age  CGPA  Attendance
0    Amit       1        CSE  20.0   8.5   90.000000
1   Priya       0         IT  21.0   9.1   95.000000
2   Rahul       1        ECE  20.0   7.8   85.000000
3   Sneha       0        CSE  22.0   8.9   92.000000
4   Karan       1         IT  21.0   8.8   88.000000
5  Anjali       0        ECE  21.0   9.3   96.000000
6   Vivek       1        CSE  20.0   7.5   91.111111
7    Neha       0         IT  22.0   8.8   91.000000
8   Arjun       1        ECE  21.0   8.2   89.000000
9   Pooja       0        CSE  21.0   9.0   94.000000

In [20]:
# applying one hot encoding to departrment
ohe = OneHotEncoder(sparse_output = False)
encoded = ohe.fit_transform(df[["Department"]])
encoded_df = pd.DataFrame(
    encoded,
    columns = ohe.get_feature_names_out(["Department"])
)
encoded_df

   Department_CSE  Department_ECE  Department_IT
0             1.0             0.0            0.0
1             0.0             0.0            1.0
2             0.0             1.0            0.0
3             1.0             0.0            0.0
4             0.0             0.0            1.0
5             0.0             1.0            0.0
6             1.0             0.0            0.0
7             0.0             0.0            1.0
8             0.0             1.0            0.0
9             1.0             0.0            0.0